{
 "title": "Visualizador pasos",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Días consecutivos que estuvo mejorando al dia anterior",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rabbit\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Analitica\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Mejoramiento consecutivos\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Pasos diarios",
   "type": "timeseries",
   "description": "Pasos que da el usuario en un día",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"rabbit\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pasos\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Promedio Pasos Diarios",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rabbit\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Analitica\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Promedio\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Pasos Mínimos",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rabbit\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Analitica\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Minimo\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Pasos Máximos",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rabbit\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Analitica\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Maximo\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Días con más de 10mil pasos",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rabbit\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Analitica\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Mayor 10k\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Días con menos de 9980 pasos",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rabbit\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Analitica\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Menor 5k\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}